language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t etelyatnikova/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true etelyatnikova/docker-react npm run test